### PR TITLE
- use udevadm from /usr/bin instead of /sbin

### PR DESCRIPTION
**Pull request by aschnell**
The bigger part of this PR is to use udevadm from /usr/bin instead of /sbin since the latter disappears.
The smaller part of this PR is to remove the option to enable crc from XFS from mkfs.xfs since it is the default for years anyway.

### CODE REVIEW

**Comment by shundhammer** [comment]
LGTM

**Comment by wfeldt** [comment]
Please note that there are yast-storage-ng test cases checking for `/sbin/udevadm`...

**Comment by aschnell** [comment]
Those test cases deal with the code in yast2-storage-ng - which of course also needs to be adapted.

**Comment by ancorgs** [comment]
See https://trello.com/c/5MQmiuTs/3829-ostumbleweed-p5-1160890-stop-using-sbin-udevadm-symlink

**Pull request merged**
