### PR TITLE
- adapted to changed nvme json output (bsc#1218306)

### PR DESCRIPTION
**Pull request by aschnell**

### CODE REVIEW

**Comment by DimStar77** [comment]
Technically, libstorage-ng should now conflict with nvme-cli < 2.7 ( to ensure we don't run this against nvme-cli 2.6 where HostID is used)

**Comment by DimStar77** [comment]
And take into account https://github.com/linux-nvme/nvme-cli/issues/2166 - this is supposedly being reverted in nvme

**Comment by igaw** [comment]
Yes, the idea is that we have a stable JSON output. Thus I rather revert all field name changes in nvme-cli and you don't have to touch your parser.

**Comment by igaw** [comment]
I verify that `nvme list-subsys -o json` will give out the same field names as with v2.6. I'll also double check if any other field name has changed. Sorry for the mess.

**Comment by aschnell** [comment]
OK, surely I changed the parser to handle the old and new text. But fixing it in nvme is even better.

**Pull request merged**
