### PR TITLE
test: Run 'test_big_numbers' only if 'long double' is supported

### PR DESCRIPTION
**Pull request by ggardet**
It fixes ARM check: #440 
boo#1078997

### CODE REVIEW

**Comment by aschnell** [comment]
Good to see that it helps.

But please only disable those three tests that fail, not the complete function. Also add a check
for "16.01 EiB"  to overflow. That should still work.

**Comment by ggardet** [comment]
As long as 'long double' is the same as 'double', all 'test_big_numbers' should be disabled since precision is not enough to handle them correctly. We have 15 digits of precision in decimal which is much more than 1 EiB. So, I think it does not make sense to enable those tests at all for ARM32.

**Comment by ggardet** [comment]
@aschnell, what do you think about my last proposition? It is quite important, since it breaks ARM32 flavors.

**Comment by aschnell** [comment]
Superseded by https://github.com/openSUSE/libstorage-ng/pull/459.

**Pull request closed without merging**
