### PR TITLE
- initialise and log variable

### PR DESCRIPTION
**Pull request by aschnell**

### CODE REVIEW

**Comment by wfeldt** [comment]
lgtm

**Comment by mvidner** [comment]
LGTM.
The compiler warned about it, right?

**Comment by aschnell** [comment]
No, not the compiler but coverity found the issue, see https://scan.coverity.com/projects/libstorage-ng.

**Comment by aschnell** [comment]
The compiler can warn with the -Weffc++ option but that gives so many warnings that it's barely useable.

**Pull request merged**
