### PR TITLE
Allow bcache to have partitions

### PR DESCRIPTION
**Pull request by jreidinger**

### CODE REVIEW

**Comment by aschnell** [comment]
Did you run utils/generate-downcast.py to generate bindings/storage-downcast.i (first run make doc)? The file storage-downcast.i may change.

Apart from that LGTM.

**Comment by jreidinger** [comment]
@aschnell no, will do it. Thanks. I also have to add fate number to commit message.

**Comment by jreidinger** [comment]
@aschnell btw this info is not in README, should I add it? Maybe to section about submission or compiling?

**Comment by aschnell** [comment]
Sure you may improve README. But that does not block merging this PR.

**Pull request merged**
