### PR TITLE
DO NOT MERGE test: fix changelog order automatically

### PR DESCRIPTION
**Pull request by jsrain**

### CODE REVIEW

**Comment by wfeldt** [comment]
NO!

The git history is completely messed up in those travis builds! (And only in travis.) We must find out why. Fixing the log will just create a bunch of weird log entries.

**Comment by jsrain** [comment]
You are right, I just wanted to give it a try (and am fine just closing/rejecting this PR).
The question for me is: Why does git2log behave so differently in the Travis environment? I don't think that Travis can take all the blame here - the environment is different, but git2log should be able to cope with it (like it does with different locale settings)

**Comment by wfeldt** [comment]
I think it's the `--depth-50` travis uses when cloning the repo.

**Comment by jsrain** [comment]
https://github.com/openSUSE/libstorage-ng/pull/456 seems to solve the problem.

**Pull request closed without merging**
