### PR TITLE
Add libstorage-ng-lang Recommends

### PR DESCRIPTION
**Pull request by zaitor**
Add missing libstorage-ng-lang Recommends

### CODE REVIEW

**Comment by aschnell** [comment]
LGTM. Thanks.

**Comment by aschnell** [comment]
On the other hand there is already a "Requires: %{name}-lang" in line 74. Did you have any problems without the "Recommends"?

**Comment by DimStar77** [comment]
Tjis change is wrong.

Since there is no libstorage-ng binary, the recommends in the preamble is useless

What he meant to do was replacing the requires in libstorage-ng1 with recommends (which is following what all pavkages do for lang)

**Comment by aschnell** [comment]
I also just read the automatic reject mail. Reverting.

**Comment by DimStar77** [comment]
> I also just read the automatic reject mail. Reverting.

Automatic? I'm not yet a bot :) but future might change that, who knows

**Comment by DimStar77** [comment]
For reference, the intention was to fix

https://lists.opensuse.org/opensuse-factory/2018-01/msg00383.html

**Comment by zaitor** [comment]
Just to confirm, that was the exact problem I was trying to fix - sorry about the cockup, that is what happens when you rush to do a quick edit in webview :-)

**Pull request merged**
