### PR TITLE
- add support for RAID metadata versions 1.1 and 1.2 (for bsc#1168914)

### PR DESCRIPTION
**Pull request by aschnell**

### CODE REVIEW

**Comment by joseivanlopez** [comment]
After this changes, unit tests are failing in YaST because differences in Md sizes. Is that expected? Are the new sizes the correct?

**Comment by aschnell** [comment]
Yes, I had to adjust the size calculation so minor changes are expected. So you can just adjust the sizes. Sorry for the inconvenience.

**Comment by joseivanlopez** [comment]
I see the submission is failing in IBS: https://build.suse.de/package/show/Devel:YaST:Head/libstorage-ng.

**Comment by aschnell** [comment]
> I see the submission is failing in IBS: https://build.suse.de/package/show/Devel:YaST:Head/libstorage-ng.

Only for SUSE_Factory_Head due to ruby.h not found. Seems unrelated to the PR. And it works in OBS for Factory and Tumbleweed. Looks more like a problem of SUSE_Factory_Head to me.

**Pull request merged**
